apiVersion: policies.kyverno.io/v1beta1
kind: ValidatingPolicy
metadata:
  name: no-unauthenticated-calls
spec:
  evaluation:
    mode: Envoy
  variables:
    - name: isPublicPath
      expression: |
        object.attributes.request.http.method == "OPTIONS" ||
        object.attributes.request.http.path.startsWith("/.well-known/")
    - name: jwks
      expression: jwks.Fetch("http://keycloak-http.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs")
    - name: jwtString
      expression: |
        variables.isPublicPath || !("authorization" in object.attributes.request.http.headers) ? "" :
          (object.attributes.request.http.headers["authorization"].startsWith("Bearer ") ?
            object.attributes.request.http.headers["authorization"].split(" ")[1] : "")
    - name: decodedJwt
      expression: |
        variables.jwtString == "" ?
          jwt.Decode("eyJhbGciOiJIUzI1NiJ9.e30.invalid", variables.jwks) :
          jwt.Decode(variables.jwtString, variables.jwks)
    - name: isAllowedGroup
      expression: |
        ("groups" in variables.decodedJwt.Claims) &&
        variables.decodedJwt.Claims["groups"].exists(g, g == "kube-dev" || g == "kube-admin")
  validations:
    - expression: |
        variables.isPublicPath ?
          envoy.Allowed().Response() :
          (variables.jwtString != "" && variables.decodedJwt.Valid && variables.isAllowedGroup ?
            envoy.Allowed().Response() : envoy.Denied(401).Response())
